name: Deploy Para Ambiente Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    environment: app-user-registration-production
    runs-on: [self-hosted, production-runner]
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login no Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
          docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REGISTRY }}

      - name: Build da imagem
        run: |
          docker build -t ${{ secrets.AWS_ECR_REPOSITORY }} .

      - name: Tag da imagem para o ECR
        run: |
          docker tag ${{ secrets.AWS_ECR_REPOSITORY }}:latest ${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.AWS_ECR_REPOSITORY }}

      - name: Enviar a Imagem para o Amazon ECR
        run: |
          docker push ${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.AWS_ECR_REPOSITORY }}

      - name: Parar e remover containers antigos
        run: |
          sudo docker stop ${{ secrets.AWS_ECR_REPOSITORY }} || true
          sudo docker rm ${{ secrets.AWS_ECR_REPOSITORY }} || true

      - name: Subir novos containers
        run: |          
          sudo docker run -d --restart=always --name ${{ secrets.AWS_ECR_REPOSITORY }} -p 80:5000 ${{ secrets.AWS_ECR_REPOSITORY }}:latest

      - name: Cleanup imagens antigas
        run: | 
          docker image prune -f 
